global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets: ['service_a:5000', 'service_b:5000', 'service_c:5000', 'service_d:5000']
    metrics_path: '/metrics'

  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:5000']
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.+)'
        replacement: 'monitoring_${1}'

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    metrics_path: '/metrics' 