SensorGateway:
  request_latency: 'monitoring_service_a_response_time'
TempSensorAggregator:
  temperature: 'monitoring_service_b_memory_usage'
PressureSensorAggregator:
  pressure: 'monitoring_service_c_memory_usage'
ReactorControl:
  control_loop_latency: 'monitoring_service_d_response_time'
CoolantPumpController:
  flow_rate: 'monitoring_service_d_cpu_usage'
  vibration: 'node_load1' 